{{ if .Values.secretEnv }}
{{- range $key := .Values.secretEnv }}
{{ if $key.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wekan.fullname" $ }}-secret
type: Opaque
data:
{{ $key.name }}: {{ $key.value | b64enc }}
{{ end }}
{{- end}}
{{ end }}
